muttleyxd/arma3-unix-launcher

MainForm.glade
Adds sorting both the Workshop and Custom list by: Enabled, Name and WorkshopID/Path
=> Add sorting to mod lists

README.md
=> add missing dependency on Debian based distros

src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp
also fixed customParameters not working
=> ui: add support for Contact and Global Mobilization DLCs

src/arma3-unix-launcher/mainwindow.cpp
allow selecting multiple directories when adding mods
also small warning fix
=> allow selecting multiple directories when adding mods

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher-library/steam_utils.cpp, src/arma3-unix-launcher/main.cpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp
=> Add Disable esync option for Proton.

src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.h, src/arma3-unix-launcher/mainwindow.ui, src/steam-integration/CMakeLists.txt, src/steam-integration/steam_integration.cpp
=> Fix Steam API issues, Fix exporting workshop mods to txt file and implement uncheck all mods

.drone.yml, tools/ci/build-package.sh, tools/ci/docker/Dockerfile.a3ul_appimage_build, tools/ci/packaging/appimage/Qt-5.14.2-LICENSE.txt, tools/ci/packaging/appimage/build.sh
=> drone: add AppImage build

src/arma3-unix-launcher-library/arma3client.cpp, src/common/CMakeLists.txt, src/common/std_utils.cpp, src/common/std_utils.hpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp, tests/unit/common/CMakeLists.txt, tests/unit/mock/std_utils.hpp
this will launch Arma 3 with or without steam-runtime, depending if it's needed
fixes #126
=> launcher: add autodetection of libpng12

cmake/external_dependencies.cmake, src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher-library/steam_utils.cpp, src/arma3-unix-launcher-library/steam_utils.hpp, src/common/filesystem_utils.cpp, src/common/filesystem_utils.hpp, src/common/std_utils.cpp, src/steam-integration/steam_integration.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp, tests/unit/arma3-unix-launcher-library/test_steam_utils.cpp, tests/unit/arma3-unix-launcher-library/test_vdf.cpp, tests/unit/mock/filesystem_utils.hpp, tests/unit/mock/std_utils.hpp, tests/unit/mock/steam_utils.hpp, tools/ci/docker/Dockerfile.a3ul_archlinux_build
=> Fix crash when Flatpak Steam is used

external/QTDark/QTDark.stylesheet, src/common/filesystem_utils.cpp
fixes #139 
also fixed white background on buttons when using `QTDark` theme
=> Fix crash with empty workshop dir and fix QTDark theme

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher-library/mod.cpp, src/arma3-unix-launcher-library/mod.hpp, src/arma3-unix-launcher/CMakeLists.txt, src/arma3-unix-launcher/html_preset_parser.cpp, src/arma3-unix-launcher/main.cpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.h, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/modtablewidget.cpp, src/arma3-unix-launcher/modtablewidget.h, src/arma3-unix-launcher/settings.cpp, src/arma3-unix-launcher/settings.hpp, src/arma3-unix-launcher/ui_mod.hpp, tests/fuzzing/arma3-unix-launcher-library/test_cppfilter_fuzz.cpp, tests/fuzzing/arma3-unix-launcher-library/test_mod_fuzz.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp, tests/unit/arma3-unix-launcher-library/test_mod.cpp, tests/unit/mock/mod.hpp
=> launcher: unified modlist, which supports reordering

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher/main.cpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.h, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp
=> launcher: add option to provide custom environment variables

.github/workflows/mac_os_x_check.yml, .github/workflows/mac_os_x_release.yml, src/arma3-unix-launcher-library/arma3client.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp
this fixes launcher crashing when GCC 10 is not installed
=> ci: mac: build with -static-libgcc

.github/workflows/mac_os_x_check.yml, .github/workflows/mac_os_x_release.yml, src/arma3-unix-launcher-library/arma3client.hpp, src/steam-integration/exceptions/steam_api_failed.hpp, src/steam-integration/steam_integration.cpp
- fix parameter name in steam-integration
- fix possible crash in steam-integration
- add Art of War DLC to exclusion list (fixes #152)
- specify Qt5 as default on Mac CI (Qt6 installs when `qt` package is selected)
=> Small bug fixes

src/arma3-unix-launcher-library/arma3client.cpp
=> library: arma3client: replace quotes in mod name with underscore

src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp
adds "CSLA" to the exclusion list, and creates a checkbox to enable it in Parameters :)
=> Add CSLA DLC to Parameters

src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher/mainwindow.cpp
Fix Western Sahara CDLC support, it should be 'WS' not 'ws'.
=> Fix Western Sahara CDLC support

cmake/external_dependencies.cmake
Ubuntu 20.04 provides too old spdlog and fmt libraries, so git versions are used.
Fixes #176
=> cmake: external_dependencies: fix fmt and spdlog on Ubuntu 20.04

src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/settings.cpp
=> Fix environment variables

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/mod.cpp, src/arma3-unix-launcher/main.cpp, src/arma3-unix-launcher/mainwindow.cpp, src/common/fmt_custom_formatters.hpp, src/dayz-linux-launcher-library/dayzclient.cpp, src/dayz-linux-launcher/main.cpp, src/dayz-linux-launcher/mainwindow.cpp, tests/fuzzing/arma3-unix-launcher-library/CMakeLists.txt, tests/unit/arma3-unix-launcher-library/CMakeLists.txt, tests/unit/arma3-unix-launcher-library/test_mod.cpp
=> library: mod: fix error when parsing keys without values

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/mod.cpp, src/arma3-unix-launcher-library/steam_utils.cpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/settings.cpp, src/common/fmt_custom_formatters.hpp, src/common/update_checker.cpp, src/common/update_checker.hpp, src/dayz-linux-launcher-library/dayzclient.cpp, src/dayz-linux-launcher-library/dayzclient.hpp, src/dayz-linux-launcher/mainwindow.cpp, src/dayz-linux-launcher/settings.cpp, src/steam-integration/steam_integration.cpp, src/steam-integration/steam_integration.hpp, src/steam-integration/steam_integration_stub.cpp, tests/unit/common/test_std_utils.cpp
=> library: fix Flatpak having empty environment variables parameter

README.md
You might also wish to change the name of the repository to "arma3-dayz-unix-launcher."
=> Initial DayZ Documentation

README.md
Wrong link, it should not point to the edit version :wink:
Fixes #236
=> Linkfix in README.md

src/arma3-unix-launcher-library/arma3client.cpp, src/arma3-unix-launcher-library/steam_utils.cpp, src/arma3-unix-launcher/main.cpp, src/dayz-linux-launcher-library/dayzclient.cpp, src/dayz-linux-launcher/main.cpp, tests/unit/arma3-unix-launcher-library/test_arma3client.cpp, tests/unit/arma3-unix-launcher-library/test_steam_utils.cpp
=> launcher, library: fix Steam integration parameter, improve behavior when workshop dir is missing

.github/workflows/linux_packages.yml, .github/workflows/linux_test_builds.yml, src/dayz-linux-launcher/main.cpp
=> fix dayz launcher

src/arma3-unix-launcher/main.cpp, src/dayz-linux-launcher/main.cpp
This reverts commit d505a29e187092168bdabe334698885e614a82a3.
fixes #243
=> Revert "launcher: disable Steam integration when parameter is passed"

src/arma3-unix-launcher-library/arma3client.hpp, src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp
=> feat: Add Spearhead 1944 CDLC

src/dayz-linux-launcher/mainwindow.cpp
fixes build failure for the dayz launcher
=> fix: apply #262 to the dayz launcher

src/arma3-unix-launcher/mainwindow.cpp, src/arma3-unix-launcher/mainwindow.h, src/arma3-unix-launcher/mainwindow.ui, src/arma3-unix-launcher/settings.cpp
=> Add support for custom profiles directory

cmake/external_dependencies.cmake, src/common/CMakeLists.txt, src/common/fmt_custom_formatters.hpp
=> Fixed compilation errors
